INSERT INTO `nationality` (`Nationality_Id`, `Nationality_En`, `Nationality_Fr`) 
VALUES (1,’Afghan’,'Afghane'),(2,’Albanian’,'Albanaise'),(3,’Algerian’,'Algérienne'),
(4,’American’,'Americaine'),(5,’Andorran’,'Andorrane'),(6,’Angolan’, 'Angolaise'),
(7,’Antiguans’,'Antiguaise'),(8,’Argentinean’,'Argentine'),(9,’Armenian’,'Armenienne'),
(10,’Australian’,'Australienne'),(11,’Austrian’,'Autrichienne'),(12,’Azerbaijani’,'Azerbaïdjanaise'),
(13,’Bahamian’,'Bahamienne'),(14,’Bahraini’,'Bahreïnienne'),(15,’Bangladeshi’,'Bangladaise'),
(16,’Barbadian’,'Barbadienne'),(17,’Barbudans’,'Barbudane'),(18,’Batswana’,'Botswanaise'),
(19,’Belarusian’,'Bielorusse'),(20,’Belgian’,'Belge'),(21,’Belizean’,'Bélizienne'),
(22,’Beninese’,'Béninoise'),(23,’Bhutanese’,'Bhoutanaise'),(24,’Bolivian’,'Bolivienne'),
(25,’Bosnian’,'Bosniaque'),(26,’Brazilian’,'Brezilienne'),(27,’British’,'Anglaise'),
(28,’Bruneian’,'Brunéienne'),(29,’Bulgarian’,'Bulgare'),(30,’Burkinabe’,'Burkinabée'),
(31,’Burmese’,'Birmane'),(32,’Burundian’,'Burundaise'),(33,’Cambodian’,'Cambodgienne'),
(34,’Cameroonian’,'Camerounaise'),(35,’Canadian’,'Canadienne'),(36,’Cape_Verdean’,'Cap-Verdienne'),
(37,’Central_African’,'Centrafricaine'),(38,’Chadian’,'Tchadienne'),(39,’Chilean’,'Chilienne'),
(40,’Chinese’,'Chinoise'),(41,’Colombian’,'Colombienne'),(42,’Comoran’,'Comorienne'),
(43,’Congolese’,'Congolaise'),(44,’Congolese’,'Congolaise'),(45,’Costa_Rican’,'Costaricaine'),
(46,’Croatian’,'Croate'),(47,’Cuban’,'Cubaine'),(48,’Cypriot’,'Chypriote'),(49,’Czech’,'Tchèque'),
(50,’Danish’,'Dannoise'),(51,’Djibouti’,'Djiboutienne'),(52,’Dominican’,'Dominicaine'),
(53,’Dominican’,'Dominicaine'),(54,’Dutch’,'Hollandaise'),(55,’Dutchman’,'Hollandaise'),
(56,’Dutchwoman’,'Hollandaise'),(57,’Timorese’,'Timoraise'),(58,’Ecuadorean’,'Équatorienne'),
(59,’Egyptian’,'Egyptienne'),(60,’Emirian’,'Emirienne'),(61,’Equatorial_Guinean’,'Équato_Guinéenne'),
(62,’Eritrean’,'Érythréenne'),(63,’Estonian’,'Estonienne'),(64,’Ethiopian’,'Éthiopienne'),
(65,’Fijian’,'Fidjienne'),(66,’Filipino’,'Philippine'),(67,’Finnish’,'Finlandaise'),(68,’French’,'Francaise'),
(69,’Gabonese’,'Gabonnaise'),(70,’Gambian’,'Gambienne'),(71,’Georgian’,'Géorgienne'),(72,’German’,'Allemande'),
(73,’Ghanaian’,'Ghanéenne'),(74,’Greek’,'Grecque'),(75,’Grenadian’,'Grenadienne'),(76,’Guatemalan’,'Guatémaltèque'),
(77,’Guinea-Bissauan’,'Bissau-Guinéenne'),(78,’Guinean’,'Guinéenne'),(79,’Guyanese’,'Guyanaise'),
(80,’Haitian’,'Haïtienne'),(81,’Herzegovinian’,'Herzegovinnaise'),(82,’Honduran’,'Hondurienne'),
(83,’Hungarian’,'Hongroise'),(84,’I-Kiribati’,'Kibirati'),(85,’Icelander’,'Islandaise'),(86,’Indian’,'Indienne'),
(87,’Indonesian’,'Indonésienne'),(88,’Iranian’,'Iranienne'),(89,’Iraqi’,'Irakienne'),(90,’Irish’,'Irlandaise'),
(91,’Irish’,'Irlandaise'),(92,’Israeli’,'Israélienne'),(93,’Italian’,'Italienne'),(94,’Ivorian’,'Ivoirienne'),
(95,’Jamaican’,'Jamaïcaine'),(96,’Japanese’,'Japonaise'),(97,’Jordanian’,'Jordanienne'),(98,’Kazakhstani’,'Kazakh'),
(99,’Kenyan’,'Kenyane'),(100,’Kittian-Nevisian’,'Saint-Christophe-et-Niévès'),(101,’Kuwaiti’,'Koweïtienne'),
(102,’Kyrgyz’,'Kirghiz'),(103,’Laotian’,'Laotienne'),(104,’Latvian’,'Lettonne'),(105,’Lebanese’,'Libanaise'),
(106,’Liberian’,'Libérienne'),(107,’Libyan’,'Libyenne'),(108,’Liechtensteiner’,'Liechtensteinoise'),
(109,’Lithuanian’,'Lituanienne'),(110,’Luxembourger’,'Luxembourgeoise'),(111,’Macedonian’,'Macédonienne'),
(112,’Malagasy’,'Malgache'),(113,’Malawian’,'Malawite'),(114,’Malaysian’,'Malaisienne'),(115,’Maldivan’,'Maldivienne'),
(116,’Malian’,'Malienne'),(117,’Maltese’,'Maltaise'),(118,’Marshallese’,'Marshallaise'),
(119,’Mauritanian’,'Mauritanienne'),(120,’Mauritian’,'Mauricienne'),(121,’Mexican’,'Mexicaine'),
(122,’Micronesian’,'Micronesienne'),(123,’Moldovan’,'Moldave'),(124,’Monacan’,'Monégasque'),
(125,’Mongolian’,'Mongole'),(126,’Moroccan’,'Marocaine'),(127,’Mosotho’,’Mosotho’),(128,’Motswana’,'Botswanaise'),
(129,’Mozambican’,'Mozambicaine'),(130,’Namibian’,'Namibienne'),(131,’Nauruan’,’Nauruane’),
(132,’Nepalese’,'Népalaise'),(133,’Netherlander’,'néerlandaise'),(134,’New_Zealander’,'Néo_Zélandaise'),
(135,’Ni-Vanuatu’,'Vanuatu'),(136,’Nicaraguan’,'Nicaraguayenne'),(137,’Nigerian’,'Nigérienne'),
(138,’Nigerien’,'Nigériane'),(139,’North Korean’,'Nord-Coréenne'),(140,’Northern Irish’,'Nord-Irlandaise'),
(141,’Norwegian’,'Norvégienne'),(142,’Omani’,'Omanaise'),(143,’Pakistani’,'Pakistanaise'),
(144,’Palauan’,'Paluanaise'),(145,’Panamanian’,'Panaméenne'),(146,’Papua-New-Guinean’,'Papouasienne'),
(147,’Paraguayan’,'Paraguayenne'),(148,’Peruvian’,'Péruvienne'),(149,’Polish’,'Polonaise'),
(150,’Portuguese’,'Portugaise'),(151,’Qatari’,'Qatarie'),(152,’Romanian’,'Roumaine'),(153,’Russian’,'Russe'),
(154,’Rwandan’,'Rwandaise'),(155,’Saint Lucian’,'Saint-Lucienne'),(156,’Salvadoran’,'Salvadorienne'),
(157,’Samoan’,'Samoanne'),(158,’San_Marinese’,'Saint-Marinnaise'),(159,’Sao Tomean’, 'Sao-Tomene'),
(160,’Saudi’,'Saoudien'),(161,’Scottish’,'Ecossaise'),(162,’Senegalese’,'Senegalaise'),(163,’Serbian’,'Serbe'),
(164,’Seychellois’,'seychelloise'),(165,’Sierra-Leonean’,'Sierra-Léonaise'),(166,’Singaporean’,'Singapourienne'),
(167,’Slovakian’,'Slovaque'),(168,’Slovenian’,'Slovène'),(169,’Solomon Islander’,'Solomonais'),
(170,’Somali’,'Somalienne'),(171,’South_African’,'Sud-Africaine'),(172,’South_Korean’,'Sud-Coréenne'),
(173,’Spanish’,'Espagnole'),(174,’Sri_Lankan’,'Sri-Lankaise'),(175,’Sudanese’,'Soudanaise'),
(176,’Surinamer’,'Surinamienne'),(177,’Swazi’,'Swazie'),(178,’Swedish’,'Suédoise'),(179,’Swiss’,'Suisse'),
(180,’Syrian’,'Syrienne'),(181,’Taiwanese’,'Taïwanaise'),(182,’Tajik’,'Tadjik'),(183,’Tanzanian’,'Tanzanienne'),
(184,’Thai’,'Thaïlandaise'),(185,’Togolese’,'Togolaise'),(186,’Tongan’,'Tonganaise'),
(187,’Trinidadian Tobagonian’,'Trinidienne Tobagonienne'),(188,’Tunisian’,'Tunisienne'),(189,’Turkish’,'Turc'),
(190,’Tuvaluan’,'Tuvaluane'),(191,’Ugandan’,'Ougandaise'),(192,’Ukrainian’,'Ukrainienne'),
(193,’Uruguayan’,'Uruguayenne'),(194,’Uzbekistani’,'Ouzbek'),(195,’Venezuelan’,'Vénézuélienne'),
196,’Vietnamese’,'Vietnamienne'),(197,’Welsh’,'Galloise'),(198,’Yemenite’,'Yéménite'),(199,’Zambian’,'Zambienne'),
(200,’Zimbabwean’,'Zimbabwéenne');



INSERT INTO `nationality` (`Nationality_Id`, `Nationality_En`, `Nationality_Fr`) 
VALUES 
(1,’Afghan’,'Afghane'),
(2,’Albanian’,'Albanaise'),
(3,’Algerian’,'Algérienne'),
(4,’American’,'Americaine'),
(5,’Andorran’,'Andorrane'),
(6,’Angolan’, 'Angolaise'),
(7,’Antiguans’,'Antiguaise'),
(8,’Argentinean’,'Argentine'),
(9,’Armenian’,'Armenienne'),
(10,’Australian’,'Australienne'),
(11,’Austrian’,'Autrichienne'),
(12,’Azerbaijani’,'Azerbaïdjanaise'),
(13,’Bahamian’,'Bahamienne'),
(14,’Bahraini’,'Bahreïnienne'),
(15,’Bangladeshi’,'Bangladaise'),
(16,’Barbadian’,'Barbadienne'),
(17,’Barbudans’,'Barbudane'),
(18,’Batswana’,'Botswanaise'),
(19,’Belarusian’,'Bielorusse'),
(20,’Belgian’,'Belge'),
(21,’Belizean’,'Bélizienne'),
(22,’Beninese’,'Béninoise'),
(23,’Bhutanese’,'Bhoutanaise'),
(24,’Bolivian’,'Bolivienne'),
(25,’Bosnian’,'Bosniaque'),
(26,’Brazilian’,'Brezilienne'),
(27,’British’,'Anglaise'),
(28,’Bruneian’,'Brunéienne'),
(29,’Bulgarian’,'Bulgare'),
(30,’Burkinabe’,'Burkinabée'),
(31,’Burmese’,'Birmane'),
(32,’Burundian’,'Burundaise'),
(33,’Cambodian’,'Cambodgienne'),
(34,’Cameroonian’,'Camerounaise'),
(35,’Canadian’,'Canadienne'),
(36,’Cape Verdean’,'Cap-Verdienne'),
(37,’Central African’,'Centrafricaine'),
(38,’Chadian’,'Tchadienne'),
(39,’Chilean’,'Chilienne'),
(40,’Chinese’,'Chinoise'),
(41,’Colombian’,'Colombienne'),
(42,’Comoran’,'Comorienne'),
(43,’Congolese’,'Congolaise'),
(44,’Congolese’,'Congolaise'),
(45,’Costa Rican’,'Costaricaine'),
(46,’Croatian’,'Croate'),
(47,’Cuban’,'Cubaine'),
(48,’Cypriot’,'Chypriote'),
(49,’Czech’,'Tchèque'),
(50,’Danish’,'Dannoise'),
(51,’Djibouti’,'Djiboutienne'),
(52,’Dominican’,'Dominicaine'),
(53,’Dominican’,'Dominicaine'),
(54,’Dutch’,'Hollandaise'),
(55,’Dutchman’,'Hollandaise'),
(56,’Dutchwoman’,'Hollandaise'),
(57,’Timorese’,'Timoraise'),
(58,’Ecuadorean’,'Équatorienne'),
(59,’Egyptian’,'Egyptienne'),
(60,’Emirian’,'Emirienne'),
(61,’Equatorial Guinean’,'Équato-Guinéenne'),
(62,’Eritrean’,'Érythréenne'),
(63,’Estonian’,'Estonienne'),
(64,’Ethiopian’,'Éthiopienne'),
(65,’Fijian’,'Fidjienne'),
(66,’Filipino’,'Philippine'),
(67,’Finnish’,'Finlandaise'),
(68,’French’,'Francaise'),
(69,’Gabonese’,'Gabonnaise'),
(70,’Gambian’,'Gambienne'),
(71,’Georgian’,'Géorgienne'),
(72,’German’,'Allemande'),
(73,’Ghanaian’,'Ghanéenne'),
(74,’Greek’,'Grecque'),
(75,’Grenadian’,'Grenadienne'),
(76,’Guatemalan’,'Guatémaltèque'),
(77,’Guinea-Bissauan’,'Bissau-Guinéenne'),
(78,’Guinean’,'Guinéenne'),
(79,’Guyanese’,'Guyanaise'),
(80,’Haitian’,'Haïtienne'),
(81,’Herzegovinian’,'Herzegovinnaise'),
(82,’Honduran’,'Hondurienne'),
(83,’Hungarian’,'Hongroise'),
(84,’I-Kiribati’,'Kibirati'),
(85,’Icelander’,'Islandaise'),
(86,’Indian’,'Indienne'),
(87,’Indonesian’,'Indonésienne'),
(88,’Iranian’,'Iranienne'),
(89,’Iraqi’,'Irakienne'),
(90,’Irish’,'Irlandaise'),
(91,’Irish’,'Irlandaise'),
(92,’Israeli’,'Israélienne'),
(93,’Italian’,'Italienne'),
(94,’Ivorian’,'Ivoirienne'),
(95,’Jamaican’,'Jamaïcaine'),
(96,’Japanese’,'Japonaise'),
(97,’Jordanian’,'Jordanienne'),
(98,’Kazakhstani’,'Kazakh'),
(99,’Kenyan’,'Kenyane'),
(100,’Kittian-Nevisian’,'Saint-Christophe-et-Niévès'),
(101,’Kuwaiti’,'Koweïtienne'),
(102,’Kyrgyz’,'Kirghiz'),
(103,’Laotian’,'Laotienne'),
(104,’Latvian’,'Lettonne'),
(105,’Lebanese’,'Libanaise'),
(106,’Liberian’,'Libérienne'),
(107,’Libyan’,'Libyenne'),
(108,’Liechtensteiner’,'Liechtensteinoise'),
(109,’Lithuanian’,'Lituanienne'),
(110,’Luxembourger’,'Luxembourgeoise'),
(111,’Macedonian’,'Macédonienne'),
(112,’Malagasy’,'Malgache'),
(113,’Malawian’,,'Malawite'),
(114,’Malaysian’,'Malaisienne'),
(115,’Maldivan’,'Maldivienne'),
(116,’Malian’,'Malienne'),
(117,’Maltese’,'Maltaise'),
(118,’Marshallese’,'Marshallaise'),
(119,’Mauritanian’,'Mauritanienne'),
(120,’Mauritian’,'Mauricienne'),
(121,’Mexican’,'Mexicaine'),
(122,’Micronesian’,'Micronesienne'),
(123,’Moldovan’,'Moldave'),
(124,’Monacan’,'Monégasque'),
(125,’Mongolian’,'Mongole'),
(126,’Moroccan’,'Marocaine'),
(127,’Mosotho’,’Mosotho’),
(128,’Motswana’,'Botswanaise'),
(129,’Mozambican’,'Mozambicaine'),
(130,’Namibian’,'Namibienne'),
(131,’Nauruan’,’Nauruane’),
(132,’Nepalese’,'Népalaise'),
(133,’Netherlander’,'néerlandaise'),
(134,’New_Zealander’,'Néo-Zélandaise'),
(135,’Ni-Vanuatu’,'Vanuatu'),
(136,’Nicaraguan’,'Nicaraguayenne'),
(137,’Nigerian’,'Nigérienne'),
(138,’Nigerien’,'Nigériane'),
(139,’North Korean’,'Nord-Coréenne'),
(140,’Northern Irish’,'Nord-Irlandaise'),
(141,’Norwegian’,'Norvégienne'),
(142,’Omani’,'Omanaise'),
(143,’Pakistani’,'Pakistanaise'),
(144,’Palauan’,'Paluanaise'),
(145,’Panamanian’,'Panaméenne'),
(146,’Papua_New_Guinean’,'Papouasienne'),
(147,’Paraguayan’,'Paraguayenne'),
(148,’Peruvian’,'Péruvienne'),
(149,’Polish’,'Polonaise'),
(150,’Portuguese’,'Portugaise'),
(151,’Qatari’,'Qatarie'),
(152,’Romanian’,'Roumaine'),
(153,’Russian’,'Russe'),
(154,’Rwandan’,'Rwandaise'),
(155,’Saint Lucian’,'Saint-Lucienne'),
(156,’Salvadoran’,'Salvadorienne'),
(157,’Samoan’,'Samoanne'),
(158,’San Marinese’,'Saint-Marinnaise'),
(159,’Sao Tomean’, 'Sao-Tomene'),
(160,’Saudi’,'Saoudien'),
(161,’Scottish’,'Ecossaise'),
(162,’Senegalese’,'Senegalaise'),
(163,’Serbian’,'Serbe'),
(164,’Seychellois’,'seychelloise'),
(165,’Sierra Leonean’,'Sierra-Léonaise'),
(166,’Singaporean’,'Singapourienne'),
(167,’Slovakian’,'Slovaque'),
(168,’Slovenian’,'Slovène'),
(169,’Solomon Islander’,'Solomonais'),
(170,’Somali’,'Somalienne'),
(171,’South African’,'Sud-Africaine'),
(172,’South Korean’,'Sud-Coréenne'),
(173,’Spanish’,'Espagnole'),
(174,’Sri Lankan’,'Sri-Lankaise'),
(175,’Sudanese’,'Soudanaise'),
(176,’Surinamer’,'Surinamienne'),
(177,’Swazi’,'Swazie'),
(178,’Swedish’,'Suédoise'),
(179,’Swiss’,'Suisse'),
(180,’Syrian’,'Syrienne'),
(181,’Taiwanese’,'Taïwanaise'),
(182,’Tajik’,'Tadjik'),
(183,’Tanzanian’,'Tanzanienne'),
(184,’Thai’,'Thaïlandaise'),
(185,’Togolese’,'Togolaise'),
(186,’Tongan’,'Tonganaise'),
(187,’Trinidadian Tobagonian’,'Trinidienne Tobagonienne'),
(188,’Tunisian’,'Tunisienne'),
(189,’Turkish’,'Turc'),
(190,’Tuvaluan’,'Tuvaluane'),
(191,’Ugandan’,'Ougandaise'),
(192,’Ukrainian’,'Ukrainienne'),
(193,’Uruguayan’,'Uruguayenne'),
(194,’Uzbekistani’,'Ouzbek'),
(195,’Venezuelan’,'Vénézuélienne'),
(196,’Vietnamese’,'Vietnamienne'),
(197,’Welsh’,'Galloise'),
(198,’Yemenite’,'Yéménite'),
(199,’Zambian’,'Zambienne'),
(200,’Zimbabwean’,'Zimbabwéenne');


INSERT INTO `nationality` (`Nationality_Id`, `Nationality_En`, `Nationality_Fr`) VALUES (1,'Afghan','Afghane'),(2,'Albanian','Albanaise'),(3,'Algerian','Algérienne'),(4,'American','Americaine'),(5,'Andorran','Andorrane'),(6,'Angolan', 'Angolaise'),(7,'Antiguans','Antiguaise'),(8,'Argentinean','Argentine'),(9,'Armenian','Armenienne'),(10,'Australian','Australienne'),(11,'Austrian','Autrichienne'),(12,'Azerbaijani','Azerbaïdjanaise'),(13,'Bahamian','Bahamienne'),(14,'Bahraini','Bahreïnienne'),(15,'Bangladeshi','Bangladaise'),(16,'Barbadian','Barbadienne'),(17,'Barbudans','Barbudane'),(18,'Batswana','Botswanaise'),(19,'Belarusian','Bielorusse'),(20,'Belgian','Belge'),(21,'Belizean','Bélizienne'),(22,'Beninese','Béninoise'),(23,'Bhutanese','Bhoutanaise'),(24,'Bolivian','Bolivienne'),(25,'Bosnian','Bosniaque'),(26,'Brazilian','Brezilienne'),(27,'British','Anglaise'),(28,'Bruneian','Brunéienne'),(29,'Bulgarian','Bulgare'),(30,'Burkinabe','Burkinabée'),(31,'Burmese','Birmane'),(32,'Burundian','Burundaise'),(33,'Cambodian','Cambodgienne'),(34,'Cameroonian','Camerounaise'),(35,'Canadian','Canadienne'),(36,'Cape_Verdean','Cap-Verdienne'),(37,'Central_African','Centrafricaine'),(38,'Chadian','Tchadienne'),(39,'Chilean','Chilienne'),(40,'Chinese','Chinoise'),(41,'Colombian','Colombienne'),(42,'Comoran','Comorienne'),(43,'Congolese','Congolaise'),(44,'Congolese','Congolaise'),(45,'Costa_Rican','Costaricaine'),(46,'Croatian','Croate'),(47,'Cuban','Cubaine'),(48,'Cypriot','Chypriote'),(49,'Czech','Tchèque'),(50,'Danish','Dannoise'),(51,'Djibouti','Djiboutienne'),(52,'Dominican','Dominicaine'),(53,'Dominican','Dominicaine'),(54,'Dutch','Hollandaise'),(55,'Dutchman','Hollandaise'),(56,'Dutchwoman','Hollandaise'),(57,'Timorese','Timoraise'),(58,'Ecuadorean','Équatorienne'),(59,'Egyptian','Egyptienne'),(60,'Emirian','Emirienne'),(61,'Equatorial_Guinean','Équato_Guinéenne'),(62,'Eritrean','Érythréenne'),(63,'Estonian','Estonienne'),(64,'Ethiopian','Éthiopienne'),(65,'Fijian','Fidjienne'),(66,'Filipino','Philippine'),(67,'Finnish','Finlandaise'),(68,'French','Francaise'),(69,'Gabonese','Gabonnaise'),(70,'Gambian','Gambienne'),(71,'Georgian','Géorgienne'),(72,'German','Allemande'),(73,'Ghanaian','Ghanéenne'),(74,'Greek','Grecque'),(75,'Grenadian','Grenadienne'),(76,'Guatemalan','Guatémaltèque'),(77,'Guinea-Bissauan','Bissau-Guinéenne'),(78,'Guinean','Guinéenne'),(79,'Guyanese','Guyanaise'),(80,'Haitian','Haïtienne'),(81,'Herzegovinian','Herzegovinnaise'),(82,'Honduran','Hondurienne'),(83,'Hungarian','Hongroise'),(84,'I-Kiribati','Kibirati'),(85,'Icelander','Islandaise'),(86,'Indian','Indienne'),(87,'Indonesian','Indonésienne'),(88,'Iranian','Iranienne'),(89,'Iraqi','Irakienne'),(90,'Irish','Irlandaise'),(91,'Irish','Irlandaise'),(92,'Israeli','Israélienne'),(93,'Italian','Italienne'),(94,'Ivorian','Ivoirienne'),(95,'Jamaican','Jamaïcaine'),(96,'Japanese','Japonaise'),(97,'Jordanian','Jordanienne'),(98,'Kazakhstani','Kazakh'),(99,'Kenyan','Kenyane'),(100,'Kittian-Nevisian','Saint-Christophe-et-Niévès'),(101,'Kuwaiti','Koweïtienne'),(102,'Kyrgyz','Kirghiz'),(103,'Laotian','Laotienne'),(104,'Latvian','Lettonne'),(105,'Lebanese','Libanaise'),(106,'Liberian','Libérienne'),(107,'Libyan','Libyenne'),(108,'Liechtensteiner','Liechtensteinoise'),(109,'Lithuanian','Lituanienne'),(110,'Luxembourger','Luxembourgeoise'),(111,'Macedonian','Macédonienne'),(112,'Malagasy','Malgache'),(113,'Malawian','Malawite'),(114,'Malaysian','Malaisienne'),(115,'Maldivan','Maldivienne'),(116,'Malian','Malienne'),(117,'Maltese','Maltaise'),(118,'Marshallese','Marshallaise'),(119,'Mauritanian','Mauritanienne'),(120,'Mauritian','Mauricienne'),(121,'Mexican','Mexicaine'),(122,'Micronesian','Micronesienne'),(123,'Moldovan','Moldave'),(124,'Monacan','Monégasque'),(125,'Mongolian','Mongole'),(126,'Moroccan','Marocaine'),(127,'Mosotho','Mosotho'),(128,'Motswana','Botswanaise'),(129,'Mozambican','Mozambicaine'),(130,'Namibian','Namibienne'),(131,'Nauruan','Nauruane'),(132,'Nepalese','Népalaise'),(133,'Netherlander','néerlandaise'),(134,'New_Zealander','Néo_Zélandaise'),(135,'Ni-Vanuatu','Vanuatu'),(136,'Nicaraguan','Nicaraguayenne'),(137,'Nigerian','Nigérienne'),(138,'Nigerien','Nigériane'),(139,'North_Korean','Nord-Coréenne'),(140,'Northern_Irish','Nord-Irlandaise'),(141,'Norwegian','Norvégienne'),(142,'Omani','Omanaise'),(143,'Pakistani','Pakistanaise'),(144,'Palauan','Paluanaise'),(145,'Panamanian','Panaméenne'),(146,'Papua-New-Guinean','Papouasienne'),(147,'Paraguayan','Paraguayenne'),(148,'Peruvian','Péruvienne'),(149,'Polish','Polonaise'),(150,'Portuguese','Portugaise'),(151,'Qatari','Qatarie'),(152,'Romanian','Roumaine'),(153,'Russian','Russe'),(154,'Rwandan','Rwandaise'),(155,'Saint_Lucian','Saint-Lucienne'),(156,'Salvadoran','Salvadorienne'),(157,'Samoan','Samoanne'),(158,'San_Marinese','Saint-Marinnaise'),(159,'Sao_Tomean', 'Sao-Tomene'),(160,'Saudi','Saoudien'),(161,'Scottish','Ecossaise'),(162,'Senegalese','Senegalaise'),(163,'Serbian','Serbe'),(164,'Seychellois','seychelloise'),(165,'Sierra-Leonean','Sierra-Léonaise'),(166,'Singaporean','Singapourienne'),(167,'Slovakian','Slovaque'),(168,'Slovenian','Slovène'),(169,'Solomon_Islander','Solomonais'),(170,'Somali','Somalienne'),(171,'South_African','Sud-Africaine'),(172,'South_Korean','Sud-Coréenne'),(173,'Spanish','Espagnole'),(174,'Sri_Lankan','Sri-Lankaise'),(175,'Sudanese','Soudanaise'),(176,'Surinamer','Surinamienne'),(177,'Swazi','Swazie'),(178,'Swedish','Suédoise'),(179,'Swiss','Suisse'),(180,'Syrian','Syrienne'),(181,'Taiwanese','Taïwanaise'),(182,'Tajik','Tadjik'),(183,'Tanzanian','Tanzanienne'),(184,'Thai','Thaïlandaise'),(185,'Togolese','Togolaise'),(186,'Tongan','Tonganaise'),(187,'Trinidadian_Tobagonian','Trinidienne_Tobagonienne'),(188,'Tunisian','Tunisienne'),(189,'Turkish','Turc'),(190,'Tuvaluan','Tuvaluane'),(191,'Ugandan','Ougandaise'),(192,'Ukrainian','Ukrainienne'),(193,'Uruguayan','Uruguayenne'),(194,'Uzbekistani','Ouzbek'),(195,'Venezuelan','Vénézuélienne'),(196,'Vietnamese','Vietnamienne'),(197,'Welsh','Galloise'),(198,'Yemenite','Yéménite'),(199,'Zambian','Zambienne'),(200,'Zimbabwean','Zimbabwéenne');


-- phpMyAdmin SQL Dump
-- version 3.4.10.1deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jan 07, 2013 at 08:28 PM
-- Server version: 5.5.28
-- PHP Version: 5.3.10-1ubuntu3.4

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

-- --------------------------------------------------------

--
-- Table structure for table `pays`
--

CREATE TABLE IF NOT EXISTS `pays` (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `code` int(3) NOT NULL,
  `alpha2` varchar(2) NOT NULL,
  `alpha3` varchar(3) NOT NULL,
  `nom_en_gb` varchar(45) NOT NULL,
  `nom_fr_fr` varchar(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `alpha2` (`alpha2`),
  UNIQUE KEY `alpha3` (`alpha3`),
  UNIQUE KEY `code_unique` (`code`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=242 ;

--
-- Dumping data for table `pays`
--

INSERT INTO `Country` (`Country_id`, `Country_code`, `Country_alpha2`, `Country_alpha3`, `Country_en_gb`, `Country_fr_fr`) VALUES
(1, 4, 'AF', 'AFG', 'Afghanistan', 'Afghanistan'),
(2, 8, 'AL', 'ALB', 'Albania', 'Albanie'),
(3, 10, 'AQ', 'ATA', 'Antarctica', 'Antarctique'),
(4, 12, 'DZ', 'DZA', 'Algeria', 'Algérie'),
(5, 16, 'AS', 'ASM', 'American Samoa', 'Samoa Américaines'),
(6, 20, 'AD', 'AND', 'Andorra', 'Andorre'),
(7, 24, 'AO', 'AGO', 'Angola', 'Angola'),
(8, 28, 'AG', 'ATG', 'Antigua and Barbuda', 'Antigua-et-Barbuda'),
(9, 31, 'AZ', 'AZE', 'Azerbaijan', 'Azerbaïdjan'),
(10, 32, 'AR', 'ARG', 'Argentina', 'Argentine'),
(11, 36, 'AU', 'AUS', 'Australia', 'Australie'),
(12, 40, 'AT', 'AUT', 'Austria', 'Autriche'),
(13, 44, 'BS', 'BHS', 'Bahamas', 'Bahamas'),
(14, 48, 'BH', 'BHR', 'Bahrain', 'Bahreïn'),
(15, 50, 'BD', 'BGD', 'Bangladesh', 'Bangladesh'),
(16, 51, 'AM', 'ARM', 'Armenia', 'Arménie'),
(17, 52, 'BB', 'BRB', 'Barbados', 'Barbade'),
(18, 56, 'BE', 'BEL', 'Belgium', 'Belgique'),
(19, 60, 'BM', 'BMU', 'Bermuda', 'Bermudes'),
(20, 64, 'BT', 'BTN', 'Bhutan', 'Bhoutan'),
(21, 68, 'BO', 'BOL', 'Bolivia', 'Bolivie'),
(22, 70, 'BA', 'BIH', 'Bosnia and Herzegovina', 'Bosnie-Herzégovine'),
(23, 72, 'BW', 'BWA', 'Botswana', 'Botswana'),
(24, 74, 'BV', 'BVT', 'Bouvet Island', 'Île Bouvet'),
(25, 76, 'BR', 'BRA', 'Brazil', 'Brésil'),
(26, 84, 'BZ', 'BLZ', 'Belize', 'Belize'),
(27, 86, 'IO', 'IOT', 'British Indian Ocean Territory', 'Territoire Britannique de l''Océan Indien'),
(28, 90, 'SB', 'SLB', 'Solomon Islands', 'Îles Salomon'),
(29, 92, 'VG', 'VGB', 'British Virgin Islands', 'Îles Vierges Britanniques'),
(30, 96, 'BN', 'BRN', 'Brunei Darussalam', 'Brunéi Darussalam'),
(31, 100, 'BG', 'BGR', 'Bulgaria', 'Bulgarie'),
(32, 104, 'MM', 'MMR', 'Myanmar', 'Myanmar'),
(33, 108, 'BI', 'BDI', 'Burundi', 'Burundi'),
(34, 112, 'BY', 'BLR', 'Belarus', 'Bélarus'),
(35, 116, 'KH', 'KHM', 'Cambodia', 'Cambodge'),
(36, 120, 'CM', 'CMR', 'Cameroon', 'Cameroun'),
(37, 124, 'CA', 'CAN', 'Canada', 'Canada'),
(38, 132, 'CV', 'CPV', 'Cape Verde', 'Cap-vert'),
(39, 136, 'KY', 'CYM', 'Cayman Islands', 'Îles Caïmanes'),
(40, 140, 'CF', 'CAF', 'Central African', 'République Centrafricaine'),
(41, 144, 'LK', 'LKA', 'Sri Lanka', 'Sri Lanka'),
(42, 148, 'TD', 'TCD', 'Chad', 'Tchad'),
(43, 152, 'CL', 'CHL', 'Chile', 'Chili'),
(44, 156, 'CN', 'CHN', 'China', 'Chine'),
(45, 158, 'TW', 'TWN', 'Taiwan', 'Taïwan'),
(46, 162, 'CX', 'CXR', 'Christmas Island', 'Île Christmas'),
(47, 166, 'CC', 'CCK', 'Cocos (Keeling) Islands', 'Îles Cocos (Keeling)'),
(48, 170, 'CO', 'COL', 'Colombia', 'Colombie'),
(49, 174, 'KM', 'COM', 'Comoros', 'Comores'),
(50, 175, 'YT', 'MYT', 'Mayotte', 'Mayotte'),
(51, 178, 'CG', 'COG', 'Republic of the Congo', 'République du Congo'),
(52, 180, 'CD', 'COD', 'The Democratic Republic Of The Congo', 'République Démocratique du Congo'),
(53, 184, 'CK', 'COK', 'Cook Islands', 'Îles Cook'),
(54, 188, 'CR', 'CRI', 'Costa Rica', 'Costa Rica'),
(55, 191, 'HR', 'HRV', 'Croatia', 'Croatie'),
(56, 192, 'CU', 'CUB', 'Cuba', 'Cuba'),
(57, 196, 'CY', 'CYP', 'Cyprus', 'Chypre'),
(58, 203, 'CZ', 'CZE', 'Czech Republic', 'République Tchèque'),
(59, 204, 'BJ', 'BEN', 'Benin', 'Bénin'),
(60, 208, 'DK', 'DNK', 'Denmark', 'Danemark'),
(61, 212, 'DM', 'DMA', 'Dominica', 'Dominique'),
(62, 214, 'DO', 'DOM', 'Dominican Republic', 'République Dominicaine'),
(63, 218, 'EC', 'ECU', 'Ecuador', 'Équateur'),
(64, 222, 'SV', 'SLV', 'El Salvador', 'El Salvador'),
(65, 226, 'GQ', 'GNQ', 'Equatorial Guinea', 'Guinée Équatoriale'),
(66, 231, 'ET', 'ETH', 'Ethiopia', 'Éthiopie'),
(67, 232, 'ER', 'ERI', 'Eritrea', 'Érythrée'),
(68, 233, 'EE', 'EST', 'Estonia', 'Estonie'),
(69, 234, 'FO', 'FRO', 'Faroe Islands', 'Îles Féroé'),
(70, 238, 'FK', 'FLK', 'Falkland Islands', 'Îles (malvinas) Falkland'),
(71, 239, 'GS', 'SGS', 'South Georgia and the South Sandwich Islands', 'Géorgie du Sud et les Îles Sandwich du Sud'),
(72, 242, 'FJ', 'FJI', 'Fiji', 'Fidji'),
(73, 246, 'FI', 'FIN', 'Finland', 'Finlande'),
(74, 248, 'AX', 'ALA', 'Åland Islands', 'Îles Åland'),
(75, 250, 'FR', 'FRA', 'France', 'France'),
(76, 254, 'GF', 'GUF', 'French Guiana', 'Guyane Française'),
(77, 258, 'PF', 'PYF', 'French Polynesia', 'Polynésie Française'),
(78, 260, 'TF', 'ATF', 'French Southern Territories', 'Terres Australes Françaises'),
(79, 262, 'DJ', 'DJI', 'Djibouti', 'Djibouti'),
(80, 266, 'GA', 'GAB', 'Gabon', 'Gabon'),
(81, 268, 'GE', 'GEO', 'Georgia', 'Géorgie'),
(82, 270, 'GM', 'GMB', 'Gambia', 'Gambie'),
(83, 275, 'PS', 'PSE', 'Occupied Palestinian Territory', 'Territoire Palestinien Occupé'),
(84, 276, 'DE', 'DEU', 'Germany', 'Allemagne'),
(85, 288, 'GH', 'GHA', 'Ghana', 'Ghana'),
(86, 292, 'GI', 'GIB', 'Gibraltar', 'Gibraltar'),
(87, 296, 'KI', 'KIR', 'Kiribati', 'Kiribati'),
(88, 300, 'GR', 'GRC', 'Greece', 'Grèce'),
(89, 304, 'GL', 'GRL', 'Greenland', 'Groenland'),
(90, 308, 'GD', 'GRD', 'Grenada', 'Grenade'),
(91, 312, 'GP', 'GLP', 'Guadeloupe', 'Guadeloupe'),
(92, 316, 'GU', 'GUM', 'Guam', 'Guam'),
(93, 320, 'GT', 'GTM', 'Guatemala', 'Guatemala'),
(94, 324, 'GN', 'GIN', 'Guinea', 'Guinée'),
(95, 328, 'GY', 'GUY', 'Guyana', 'Guyana'),
(96, 332, 'HT', 'HTI', 'Haiti', 'Haïti'),
(97, 334, 'HM', 'HMD', 'Heard Island and McDonald Islands', 'Îles Heard et Mcdonald'),
(98, 336, 'VA', 'VAT', 'Vatican City State', 'Saint-Siège (état de la Cité du Vatican)'),
(99, 340, 'HN', 'HND', 'Honduras', 'Honduras'),
(100, 344, 'HK', 'HKG', 'Hong Kong', 'Hong-Kong'),
(101, 348, 'HU', 'HUN', 'Hungary', 'Hongrie'),
(102, 352, 'IS', 'ISL', 'Iceland', 'Islande'),
(103, 356, 'IN', 'IND', 'India', 'Inde'),
(104, 360, 'ID', 'IDN', 'Indonesia', 'Indonésie'),
(105, 364, 'IR', 'IRN', 'Islamic Republic of Iran', 'République Islamique d''Iran'),
(106, 368, 'IQ', 'IRQ', 'Iraq', 'Iraq'),
(107, 372, 'IE', 'IRL', 'Ireland', 'Irlande'),
(108, 376, 'IL', 'ISR', 'Israel', 'Israël'),
(109, 380, 'IT', 'ITA', 'Italy', 'Italie'),
(110, 384, 'CI', 'CIV', 'Côte d''Ivoire', 'Côte d''Ivoire'),
(111, 388, 'JM', 'JAM', 'Jamaica', 'Jamaïque'),
(112, 392, 'JP', 'JPN', 'Japan', 'Japon'),
(113, 398, 'KZ', 'KAZ', 'Kazakhstan', 'Kazakhstan'),
(114, 400, 'JO', 'JOR', 'Jordan', 'Jordanie'),
(115, 404, 'KE', 'KEN', 'Kenya', 'Kenya'),
(116, 408, 'KP', 'PRK', 'Democratic People''s Republic of Korea', 'République Populaire Démocratique de Corée'),
(117, 410, 'KR', 'KOR', 'Republic of Korea', 'République de Corée'),
(118, 414, 'KW', 'KWT', 'Kuwait', 'Koweït'),
(119, 417, 'KG', 'KGZ', 'Kyrgyzstan', 'Kirghizistan'),
(120, 418, 'LA', 'LAO', 'Lao People''s Democratic Republic', 'République Démocratique Populaire Lao'),
(121, 422, 'LB', 'LBN', 'Lebanon', 'Liban'),
(122, 426, 'LS', 'LSO', 'Lesotho', 'Lesotho'),
(123, 428, 'LV', 'LVA', 'Latvia', 'Lettonie'),
(124, 430, 'LR', 'LBR', 'Liberia', 'Libéria'),
(125, 434, 'LY', 'LBY', 'Libyan Arab Jamahiriya', 'Jamahiriya Arabe Libyenne'),
(126, 438, 'LI', 'LIE', 'Liechtenstein', 'Liechtenstein'),
(127, 440, 'LT', 'LTU', 'Lithuania', 'Lituanie'),
(128, 442, 'LU', 'LUX', 'Luxembourg', 'Luxembourg'),
(129, 446, 'MO', 'MAC', 'Macao', 'Macao'),
(130, 450, 'MG', 'MDG', 'Madagascar', 'Madagascar'),
(131, 454, 'MW', 'MWI', 'Malawi', 'Malawi'),
(132, 458, 'MY', 'MYS', 'Malaysia', 'Malaisie'),
(133, 462, 'MV', 'MDV', 'Maldives', 'Maldives'),
(134, 466, 'ML', 'MLI', 'Mali', 'Mali'),
(135, 470, 'MT', 'MLT', 'Malta', 'Malte'),
(136, 474, 'MQ', 'MTQ', 'Martinique', 'Martinique'),
(137, 478, 'MR', 'MRT', 'Mauritania', 'Mauritanie'),
(138, 480, 'MU', 'MUS', 'Mauritius', 'Maurice'),
(139, 484, 'MX', 'MEX', 'Mexico', 'Mexique'),
(140, 492, 'MC', 'MCO', 'Monaco', 'Monaco'),
(141, 496, 'MN', 'MNG', 'Mongolia', 'Mongolie'),
(142, 498, 'MD', 'MDA', 'Republic of Moldova', 'République de Moldova'),
(143, 500, 'MS', 'MSR', 'Montserrat', 'Montserrat'),
(144, 504, 'MA', 'MAR', 'Morocco', 'Maroc'),
(145, 508, 'MZ', 'MOZ', 'Mozambique', 'Mozambique'),
(146, 512, 'OM', 'OMN', 'Oman', 'Oman'),
(147, 516, 'NA', 'NAM', 'Namibia', 'Namibie'),
(148, 520, 'NR', 'NRU', 'Nauru', 'Nauru'),
(149, 524, 'NP', 'NPL', 'Nepal', 'Népal'),
(150, 528, 'NL', 'NLD', 'Netherlands', 'Pays-Bas'),
(151, 530, 'AN', 'ANT', 'Netherlands Antilles', 'Antilles Néerlandaises'),
(152, 533, 'AW', 'ABW', 'Aruba', 'Aruba'),
(153, 540, 'NC', 'NCL', 'New Caledonia', 'Nouvelle-Calédonie'),
(154, 548, 'VU', 'VUT', 'Vanuatu', 'Vanuatu'),
(155, 554, 'NZ', 'NZL', 'New Zealand', 'Nouvelle-Zélande'),
(156, 558, 'NI', 'NIC', 'Nicaragua', 'Nicaragua'),
(157, 562, 'NE', 'NER', 'Niger', 'Niger'),
(158, 566, 'NG', 'NGA', 'Nigeria', 'Nigéria'),
(159, 570, 'NU', 'NIU', 'Niue', 'Niué'),
(160, 574, 'NF', 'NFK', 'Norfolk Island', 'Île Norfolk'),
(161, 578, 'NO', 'NOR', 'Norway', 'Norvège'),
(162, 580, 'MP', 'MNP', 'Northern Mariana Islands', 'Îles Mariannes du Nord'),
(163, 581, 'UM', 'UMI', 'United States Minor Outlying Islands', 'Îles Mineures Éloignées des États-Unis'),
(164, 583, 'FM', 'FSM', 'Federated States of Micronesia', 'États Fédérés de Micronésie'),
(165, 584, 'MH', 'MHL', 'Marshall Islands', 'Îles Marshall'),
(166, 585, 'PW', 'PLW', 'Palau', 'Palaos'),
(167, 586, 'PK', 'PAK', 'Pakistan', 'Pakistan'),
(168, 591, 'PA', 'PAN', 'Panama', 'Panama'),
(169, 598, 'PG', 'PNG', 'Papua New Guinea', 'Papouasie-Nouvelle-Guinée'),
(170, 600, 'PY', 'PRY', 'Paraguay', 'Paraguay'),
(171, 604, 'PE', 'PER', 'Peru', 'Pérou'),
(172, 608, 'PH', 'PHL', 'Philippines', 'Philippines'),
(173, 612, 'PN', 'PCN', 'Pitcairn', 'Pitcairn'),
(174, 616, 'PL', 'POL', 'Poland', 'Pologne'),
(175, 620, 'PT', 'PRT', 'Portugal', 'Portugal'),
(176, 624, 'GW', 'GNB', 'Guinea-Bissau', 'Guinée-Bissau'),
(177, 626, 'TL', 'TLS', 'Timor-Leste', 'Timor-Leste'),
(178, 630, 'PR', 'PRI', 'Puerto Rico', 'Porto Rico'),
(179, 634, 'QA', 'QAT', 'Qatar', 'Qatar'),
(180, 638, 'RE', 'REU', 'Réunion', 'Réunion'),
(181, 642, 'RO', 'ROU', 'Romania', 'Roumanie'),
(182, 643, 'RU', 'RUS', 'Russian Federation', 'Fédération de Russie'),
(183, 646, 'RW', 'RWA', 'Rwanda', 'Rwanda'),
(184, 654, 'SH', 'SHN', 'Saint Helena', 'Sainte-Hélène'),
(185, 659, 'KN', 'KNA', 'Saint Kitts and Nevis', 'Saint-Kitts-et-Nevis'),
(186, 660, 'AI', 'AIA', 'Anguilla', 'Anguilla'),
(187, 662, 'LC', 'LCA', 'Saint Lucia', 'Sainte-Lucie'),
(188, 666, 'PM', 'SPM', 'Saint-Pierre and Miquelon', 'Saint-Pierre-et-Miquelon'),
(189, 670, 'VC', 'VCT', 'Saint Vincent and the Grenadines', 'Saint-Vincent-et-les Grenadines'),
(190, 674, 'SM', 'SMR', 'San Marino', 'Saint-Marin'),
(191, 678, 'ST', 'STP', 'Sao Tome and Principe', 'Sao Tomé-et-Principe'),
(192, 682, 'SA', 'SAU', 'Saudi Arabia', 'Arabie Saoudite'),
(193, 686, 'SN', 'SEN', 'Senegal', 'Sénégal'),
(194, 690, 'SC', 'SYC', 'Seychelles', 'Seychelles'),
(195, 694, 'SL', 'SLE', 'Sierra Leone', 'Sierra Leone'),
(196, 702, 'SG', 'SGP', 'Singapore', 'Singapour'),
(197, 703, 'SK', 'SVK', 'Slovakia', 'Slovaquie'),
(198, 704, 'VN', 'VNM', 'Vietnam', 'Viet Nam'),
(199, 705, 'SI', 'SVN', 'Slovenia', 'Slovénie'),
(200, 706, 'SO', 'SOM', 'Somalia', 'Somalie'),
(201, 710, 'ZA', 'ZAF', 'South Africa', 'Afrique du Sud'),
(202, 716, 'ZW', 'ZWE', 'Zimbabwe', 'Zimbabwe'),
(203, 724, 'ES', 'ESP', 'Spain', 'Espagne'),
(204, 732, 'EH', 'ESH', 'Western Sahara', 'Sahara Occidental'),
(205, 736, 'SD', 'SDN', 'Sudan', 'Soudan'),
(206, 740, 'SR', 'SUR', 'Suriname', 'Suriname'),
(207, 744, 'SJ', 'SJM', 'Svalbard and Jan Mayen', 'Svalbard etÎle Jan Mayen'),
(208, 748, 'SZ', 'SWZ', 'Swaziland', 'Swaziland'),
(209, 752, 'SE', 'SWE', 'Sweden', 'Suède'),
(210, 756, 'CH', 'CHE', 'Switzerland', 'Suisse'),
(211, 760, 'SY', 'SYR', 'Syrian Arab Republic', 'République Arabe Syrienne'),
(212, 762, 'TJ', 'TJK', 'Tajikistan', 'Tadjikistan'),
(213, 764, 'TH', 'THA', 'Thailand', 'Thaïlande'),
(214, 768, 'TG', 'TGO', 'Togo', 'Togo'),
(215, 772, 'TK', 'TKL', 'Tokelau', 'Tokelau'),
(216, 776, 'TO', 'TON', 'Tonga', 'Tonga'),
(217, 780, 'TT', 'TTO', 'Trinidad and Tobago', 'Trinité-et-Tobago'),
(218, 784, 'AE', 'ARE', 'United Arab Emirates', 'Émirats Arabes Unis'),
(219, 788, 'TN', 'TUN', 'Tunisia', 'Tunisie'),
(220, 792, 'TR', 'TUR', 'Turkey', 'Turquie'),
(221, 795, 'TM', 'TKM', 'Turkmenistan', 'Turkménistan'),
(222, 796, 'TC', 'TCA', 'Turks and Caicos Islands', 'Îles Turks et Caïques'),
(223, 798, 'TV', 'TUV', 'Tuvalu', 'Tuvalu'),
(224, 800, 'UG', 'UGA', 'Uganda', 'Ouganda'),
(225, 804, 'UA', 'UKR', 'Ukraine', 'Ukraine'),
(226, 807, 'MK', 'MKD', 'The Former Yugoslav Republic of Macedonia', 'L''ex-République Yougoslave de Macédoine'),
(227, 818, 'EG', 'EGY', 'Egypt', 'Égypte'),
(228, 826, 'GB', 'GBR', 'United Kingdom', 'Royaume-Uni'),
(229, 833, 'IM', 'IMN', 'Isle of Man', 'Île de Man'),
(230, 834, 'TZ', 'TZA', 'United Republic Of Tanzania', 'République-Unie de Tanzanie'),
(231, 840, 'US', 'USA', 'United States', 'États-Unis'),
(232, 850, 'VI', 'VIR', 'U.S. Virgin Islands', 'Îles Vierges des États-Unis'),
(233, 854, 'BF', 'BFA', 'Burkina Faso', 'Burkina Faso'),
(234, 858, 'UY', 'URY', 'Uruguay', 'Uruguay'),
(235, 860, 'UZ', 'UZB', 'Uzbekistan', 'Ouzbékistan'),
(236, 862, 'VE', 'VEN', 'Venezuela', 'Venezuela'),
(237, 876, 'WF', 'WLF', 'Wallis and Futuna', 'Wallis et Futuna'),
(238, 882, 'WS', 'WSM', 'Samoa', 'Samoa'),
(239, 887, 'YE', 'YEM', 'Yemen', 'Yémen'),
(240, 891, 'CS', 'SCG', 'Serbia and Montenegro', 'Serbie-et-Monténégro'),
(241, 894, 'ZM', 'ZMB', 'Zambia', 'Zambie');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
